export const FARE_MODAL_OPEN = "FARE_MODAL_OPEN";
export const FARE_MODAL_CLOSE = "FARE_MODAL_CLOSE";
export const INCREMENT_COUNTER = "INCREMENT_COUNTER";
export const DECREMENT_COUNTER = "DECREMENT_COUNTER";